apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  name: busybox
spec:
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - busybox
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: busybox
    spec:
      containers:
      - command:
        - sleep
        - "10000"
        image: busybox
        imagePullPolicy: IfNotPresent
        name: busybox
        resources: {}
        volumeMounts:
        - mountPath: /mnt/gcp
          name: gcp-pv
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: gcp-pv
        persistentVolumeClaim:
          claimName: gcp-pvc
          readOnly: true
  updateStrategy: {}
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
