apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: consul
  name: consul
spec:
  clusterIP: None
  ports:
  - name: http
    port: 8500
    targetPort: 8500
  - name: https
    port: 8443
    targetPort: 8443
  - name: rpc
    port: 8400
    targetPort: 8400
  - name: serflan-tcp
    port: 8301
    protocol: TCP
    targetPort: 8301
  - name: serflan-udp
    port: 8301
    protocol: UDP
    targetPort: 8301
  - name: serfwan-tcp
    port: 8302
    protocol: TCP
    targetPort: 8302
  - name: serfwan-udp
    port: 8302
    protocol: UDP
    targetPort: 8302
  - name: server
    port: 8300
    targetPort: 8300
  - name: consuldns
    port: 8600
    targetPort: 8600
  selector:
    app: consul
status:
  loadBalancer: {}

---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  creationTimestamp: null
  name: consul
spec:
  replicas: 3
  serviceName: consul
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: consul
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - consul
                - consul-load
                - consul-watch
            topologyKey: kubernetes.io/hostname
      containers:
      - args:
        - agent
        - -advertise=$(POD_IP)
        - -bind=0.0.0.0
        - -bootstrap-expect=3
        - -retry-join=consul-0.consul.$(NAMESPACE).svc.cluster.local
        - -retry-join=consul-1.consul.$(NAMESPACE).svc.cluster.local
        - -retry-join=consul-2.consul.$(NAMESPACE).svc.cluster.local
        - -client=0.0.0.0
        - -datacenter=gke
        - -data-dir=/consul/data
        - -domain=cluster.local
        - -encrypt=$(GOSSIP_ENCRYPTION_KEY)
        - -server
        - -disable-host-node-id
        env:
        - name: GOSSIP_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              key: gossip-encryption-key
              name: consul
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: consul:1.2.2
        lifecycle:
          preStop:
            exec:
              command:
              - consul
              - leave
        name: consul
        ports:
        - containerPort: 8500
          name: ui-port
        - containerPort: 8400
          name: alt-port
        - containerPort: 53
          name: udp-port
        - containerPort: 8443
          name: https-port
        - containerPort: 8080
          name: http-port
        - containerPort: 8301
          name: serflan
        - containerPort: 8302
          name: serfwan
        - containerPort: 8600
          name: consuldns
        - containerPort: 8300
          name: server
        resources: {}
      securityContext:
        fsGroup: 1000
      terminationGracePeriodSeconds: 10
  updateStrategy: {}
status:
  replicas: 0

---
