apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: consul-load
  name: consul-load
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - consul-load
            - consul-test
        topologyKey: kubernetes.io/hostname
  containers:
  - command:
    - curl
    - --request
    - PUT
    - --data
    - myValueFromPod
    - http://consul-0.consul.default.svc.cluster.local:8500/v1/kv/myKey
    image: sdeoras/consul
    imagePullPolicy: Always
    name: consul-load
    resources: {}
  restartPolicy: Never
status: {}
