apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: sleeping
  name: sleeping
spec:
  containers:
  - command:
    - sleep
    - "10000"
    image: ubuntu
    imagePullPolicy: IfNotPresent
    name: sleeping
    resources: {}
    volumeMounts:
    - mountPath: /mnt/secret
      name: secret-volume
  restartPolicy: Never
  volumes:
  - name: secret-volume
    secret:
      secretName: gcs-auth
status: {}
