apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: cp-gcp-pwx
spec:
  parallelism: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cp-gcp-pwx
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - cp-gcp-pwx
            topologyKey: kubernetes.io/hostname
      containers:
      - command:
        - /token/bin/cp
        - --host
        - token-server:7001
        - --job-id
        - jobs_cp_gcp_pwx
        - --batch-size
        - "100"
        - --num-batches
        - "100"
        - --source-dir
        - /mnt/gcp/imagenet/input_900
        - --destination-dir
        - /mnt/pwx/images
        - --out-dir
        - /mnt/pwx/out
        image: sdeoras/token
        imagePullPolicy: IfNotPresent
        name: cp-gcp-pwx
        resources: {}
        volumeMounts:
        - mountPath: /mnt/gcp
          name: gcp-volume
          readOnly: true
        - mountPath: /mnt/pwx/
          name: px-pvc-1
      restartPolicy: Never
      volumes:
      - name: gcp-volume
        persistentVolumeClaim:
          claimName: gcp-pvc
          readOnly: true
      - name: px-pvc-1
        persistentVolumeClaim:
          claimName: px-pvc-1
status: {}
