apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: gcp-nfs-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1T
  volumeName: gcp-nfs-pv
status: {}
