apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: gcp-pvc
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 256Gi
  volumeName: gcp-pv
status: {}
