apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: px-high-rf2
  creationTimestamp: null
  name: px-pvc-1
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: px-high-rf2
  creationTimestamp: null
  name: px-pvc-2
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: px-high-rf2
  creationTimestamp: null
  name: px-pvc-3
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
status: {}
