apiVersion: kubeflow.org/v1alpha2
kind: TFJob
metadata:
  creationTimestamp: null
  name: example-job
spec:
  tfReplicaSpecs:
    Worker:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: gcr.io/tf-on-k8s-dogfood/tf_sample:dc944ff
            name: tensorflow
            resources: {}
status:
  conditions: null
  replicaStatuses: null
