apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: access-nginx
  namespace: nginx
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          access: "true"
  podSelector:
    matchLabels:
      run: nginx
