apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: token-server
spec:
  ports:
  - port: 7001
    protocol: TCP
    targetPort: 7001
  selector:
    app: token-server
status:
  loadBalancer: {}
